---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ghcr-creds
  namespace: lokiops-web
spec:
  encryptedData:
    .dockerconfigjson: AgBvjdYp9MDl4+ouXPAMud0JJDpWWEx0q4yZuYVBeY1hymalkPVKG5YrWak7Tz2SIiypqTsSzIeZPGU7vmY/o6h0myxTmk2nxBVA6kOyVM7hHdDkggOo+Yl8WDv843dNYGaG4S2MwNeg0u7V1JAfs9wToAlVIaovS/H9oE6LAnLT9L0xyMtzH3cfphS6F07yys2mTmNfX7AOLNm3O2itq/fRu56x5U7jVeX/J2HuJKCA+6QnLBcTSHhONjRf3ASIubXICCfq1IP9DhYsUQG3i9tFjboULi4a7qw0WE6vE/u9wv1YGBDfHktHMXew1YVuABbVYNX9iycoATUzh0Spx/KP3csvB4U0qI53dxwr06qajgcnFXg+5eJ/tbC7jXezbpg+rEGn3mdWFNWQRxOeC6TK5XngJDwNEnSwnUM9iF9BnuqjTai7L1Yxk/GDzC1EusAECiX66Fqu2bD7Bk6jRau2h73Wq8BPmYsSmqJg9lnecZKGpqYcb3Y/BGv9nFtUU46Y3cyIxUHcBJ2rDB6DWUQCdE3Eor+gwFMOxIK3XdVJA0skQkSdfKJL1QM6/HuaNWwC6h4kK+8sH69Q65HlI83dXElMGQaoEh1id1RE8Ujvxaf83d1CGbzxnXjrW2v4z6xGHyH8QWHfTdz1uORECftdYPRLjAn0Yr4qlrndDmJZPSQvSYSql4ep+qxF6B2M7GJbjfN1npCBaTZOuR8zIwEA/2dfuWrPrYJZW4y3ypJ0gWXbMEpo89qpS9A9Yq5+doQe1NfYqCtqebaKHBwT7Tmu+D9p8/7aiGggNtLHPYYGQ+MdV5N/HpLtHirrcWFGSXU3JgROTOIk1/gx8fZswiqq6a0+8JUISVCTm5/QivigL+vOs8tI45Wkp3lV1S3Q7AnA42Obw3ekoQjoYOFgOE3xACMVMt8SYb7xCccZ0xnQsSo4OA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ghcr-creds
      namespace: lokiops-web
    type: kubernetes.io/dockerconfigjson
