---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: lokiops-web
spec:
  encryptedData:
    .dockerconfigjson: AgDL01lK96W7e3GwiO+rWshMN8qSuG206I4dBOCZDeMxvak3ms0a6bVcx5pr/fzd33xHl9FyaYJ+RQxt8r7V1no/EzB86NWT9i8eie5onrlZmBoCIYAX0g1e/QacvJNGrXMNsHw1BUIskIFwhYuWBriH772y9l75WZIFJg039vLlfwyiu+iW+DkqU14apbMJu5DzqzDEI2e0SBNbZzah0CD28lVmIil2s1jVPIWqRUdrSiX9e2GRM9JwANOUgCNJxcIrAgU4MsFsupF1OFcu+k9S07ME65wfiCsEDSpDSrbE8yzCzm8dxNyslvBQIOCjIQPTmUtisrs9F4oqiOnFKv9p5E+sRD+Cs/8r1L5O38W5KpXQeEDg1r5TW1NJcP4ayNNFu0K6AD8p3rU3vqRLScMRW/TCfhgkCO3awpeczac1S+Myt9uWgXuujyaoTr6/9jcb9xk17gG9vtR9NqKfYzSc4rgxsj2+OoYmNOc4QOxHrYF4Ohdr4US9DZSZVS6kwOG7qAovWEOrFZWfMZF5SKKLNf2U1iAaFd4x/HMJylkZMMW0ncbaaZ1QO7xpfVGBij6qKxsqWBQRhkioXxoJI+RTOwczVMSM2CLk8wZGF60d3WSfNM0WC1odswSWSiec1HTTYurh691vzitDLaFSyMAPnVjhEQ4OtxsLPpZ9svxa2R1MsRaz78LutEAL4P52lgmmDW9H29o+ni+SO1ia5NP/Iytdg5YFYXtQQVnVonXv6BqpllADy4BkAPjMfAmqqmsaTmlQYx9foBWuJNaGRDGRGLPpnJiAo/3mAUPrVxhLf+FLpwCLpSp6sCjwZiY/khvBgbGhBwVXscDRkhwfOiwvls+53Dqku+5RFFvC8DWOl7pB21LHaFEYHffjcTBNU0rZa37AZ5Hja1Gmt1uuVo4SvB3drUWtkdKHVDGfJ0WOx5edvA==
  template:
    metadata:
      name: ghcr-creds
      namespace: lokiops-web
    type: kubernetes.io/dockerconfigjson
